[0m13:04:52.945181 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C269B9BDA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C26931D280>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C269CB1280>]}


============================== 13:04:52.949766 | d6c0616a-539e-4375-9965-93402daca0a3 ==============================
[0m13:04:52.949766 [info ] [MainThread]: Running with dbt=1.10.5
[0m13:04:52.949766 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\salma.mahmoud\\.dbt', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt init bi', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True'}
[0m13:04:52.975119 [debug] [MainThread]: Starter project path: C:\Users\salma.mahmoud\AppData\Roaming\Python\Python312\site-packages\dbt\include\starter_project
[0m13:04:52.975684 [info ] [MainThread]: 
Your new dbt project "bi" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m13:04:52.975684 [info ] [MainThread]: Setting up your profile.
[0m13:04:55.957489 [debug] [MainThread]: Command `dbt init` succeeded at 13:04:55.957489 after 3.18 seconds
[0m13:04:55.957489 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C26A5587A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C26AC03E90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C26A1C57F0>]}
[0m13:04:55.957489 [debug] [MainThread]: Flushing usage events
[0m13:04:57.135009 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m15:23:13.208205 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000029941102AB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000029941102F00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000029941103080>]}


============================== 15:23:13.214099 | d033be0d-c1a1-4ee9-9986-95e206dc3e6a ==============================
[0m15:23:13.214099 [info ] [MainThread]: Running with dbt=1.10.5
[0m15:23:13.216117 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\salma.mahmoud\\.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt debug', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m15:23:13.247692 [info ] [MainThread]: dbt version: 1.10.5
[0m15:23:13.247692 [info ] [MainThread]: python version: 3.12.4
[0m15:23:13.248670 [info ] [MainThread]: python path: C:\Program Files\Python312\python.exe
[0m15:23:13.248670 [info ] [MainThread]: os info: Windows-11-10.0.26100-SP0
[0m15:23:19.864517 [info ] [MainThread]: Using profiles dir at C:\Users\salma.mahmoud\.dbt
[0m15:23:19.866027 [info ] [MainThread]: Using profiles.yml file at C:\Users\salma.mahmoud\.dbt\profiles.yml
[0m15:23:19.866027 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\salma.mahmoud\cube\dbt-semantic-layer\dbt_project.yml
[0m15:23:19.867036 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m15:23:19.868036 [debug] [MainThread]: Command `dbt debug` failed at 15:23:19.868036 after 6.84 seconds
[0m15:23:19.868539 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000029941EBC1A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000029951758B30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000029942035790>]}
[0m15:23:19.868539 [debug] [MainThread]: Flushing usage events
[0m15:23:20.862511 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m15:24:32.611978 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000243D006FFB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000243D27F03B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000243D27F2810>]}


============================== 15:24:32.616261 | c620b019-5dd0-483c-b613-7bc3484a624a ==============================
[0m15:24:32.616261 [info ] [MainThread]: Running with dbt=1.10.5
[0m15:24:32.617181 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\salma.mahmoud\\.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'static_parser': 'True', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt debug', 'send_anonymous_usage_stats': 'True'}
[0m15:24:32.634462 [info ] [MainThread]: dbt version: 1.10.5
[0m15:24:32.634462 [info ] [MainThread]: python version: 3.12.4
[0m15:24:32.634462 [info ] [MainThread]: python path: C:\Program Files\Python312\python.exe
[0m15:24:32.636485 [info ] [MainThread]: os info: Windows-11-10.0.26100-SP0
[0m15:24:33.578385 [info ] [MainThread]: Using profiles dir at C:\Users\salma.mahmoud\.dbt
[0m15:24:33.579372 [info ] [MainThread]: Using profiles.yml file at C:\Users\salma.mahmoud\.dbt\profiles.yml
[0m15:24:33.580382 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\salma.mahmoud\cube\dbt-semantic-layer\dbt_project.yml
[0m15:24:33.581279 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m15:24:33.582318 [debug] [MainThread]: Command `dbt debug` failed at 15:24:33.582318 after 1.13 seconds
[0m15:24:33.582318 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000243D26F0F20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000243D38E2A80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000243E2E50920>]}
[0m15:24:33.582318 [debug] [MainThread]: Flushing usage events
[0m15:24:34.525454 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m15:34:59.014243 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026BFF026D80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026BFF027050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026BFF0260C0>]}


============================== 15:34:59.014832 | 5c505332-ef0b-46cd-ac82-d0c6385656f2 ==============================
[0m15:34:59.014832 [info ] [MainThread]: Running with dbt=1.10.5
[0m15:34:59.014832 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\salma.mahmoud\\.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt debug', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m15:34:59.036116 [info ] [MainThread]: dbt version: 1.10.5
[0m15:34:59.036116 [info ] [MainThread]: python version: 3.12.4
[0m15:34:59.036116 [info ] [MainThread]: python path: C:\Program Files\Python312\python.exe
[0m15:34:59.036116 [info ] [MainThread]: os info: Windows-11-10.0.26100-SP0
[0m15:35:00.046551 [info ] [MainThread]: Using profiles dir at C:\Users\salma.mahmoud\.dbt
[0m15:35:00.048259 [info ] [MainThread]: Using profiles.yml file at C:\Users\salma.mahmoud\.dbt\profiles.yml
[0m15:35:00.048259 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\salma.mahmoud\cube\dbt-semantic-layer\dbt_project.yml
[0m15:35:00.048259 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m15:35:00.048259 [debug] [MainThread]: Command `dbt debug` failed at 15:35:00.048259 after 1.20 seconds
[0m15:35:00.048259 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026BFC63AB70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026BFFA546B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026BFF8F41D0>]}
[0m15:35:00.048259 [debug] [MainThread]: Flushing usage events
[0m15:35:16.522503 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m16:12:51.855465 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DF29E25700>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DF29E272C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DF29E25FD0>]}


============================== 16:12:51.855465 | bef1c9ee-c2b0-4eb4-a5e6-f94c0a8b741f ==============================
[0m16:12:51.855465 [info ] [MainThread]: Running with dbt=1.10.5
[0m16:12:51.855465 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': 'C:\\Users\\salma.mahmoud\\.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'introspect': 'True', 'invocation_command': 'dbt debug', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m16:12:51.891950 [info ] [MainThread]: dbt version: 1.10.5
[0m16:12:51.892614 [info ] [MainThread]: python version: 3.12.4
[0m16:12:51.892614 [info ] [MainThread]: python path: C:\Program Files\Python312\python.exe
[0m16:12:51.893633 [info ] [MainThread]: os info: Windows-11-10.0.26100-SP0
[0m16:13:01.120677 [info ] [MainThread]: Using profiles dir at C:\Users\salma.mahmoud\.dbt
[0m16:13:01.120677 [info ] [MainThread]: Using profiles.yml file at C:\Users\salma.mahmoud\.dbt\profiles.yml
[0m16:13:01.120677 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\salma.mahmoud\cube\dbt-semantic-layer\dbt_project.yml
[0m16:13:01.120677 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m16:13:01.120677 [debug] [MainThread]: Command `dbt debug` failed at 16:13:01.120677 after 9.44 seconds
[0m16:13:01.120677 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DF2A307290>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DF3A7242C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DF3A3D0530>]}
[0m16:13:01.120677 [debug] [MainThread]: Flushing usage events
[0m16:13:02.340749 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m16:13:24.472518 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C62969C0B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C62C373170>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C62BE2A930>]}


============================== 16:13:24.476570 | e2a5689c-cd36-4449-bc40-6e68486beb8f ==============================
[0m16:13:24.476570 [info ] [MainThread]: Running with dbt=1.10.5
[0m16:13:24.476570 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': 'C:\\Users\\salma.mahmoud\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'target_path': 'None', 'invocation_command': 'dbt debug', 'send_anonymous_usage_stats': 'True'}
[0m16:13:24.495906 [info ] [MainThread]: dbt version: 1.10.5
[0m16:13:24.496907 [info ] [MainThread]: python version: 3.12.4
[0m16:13:24.496907 [info ] [MainThread]: python path: C:\Program Files\Python312\python.exe
[0m16:13:24.497816 [info ] [MainThread]: os info: Windows-11-10.0.26100-SP0
[0m16:13:25.549117 [info ] [MainThread]: Using profiles dir at C:\Users\salma.mahmoud\.dbt
[0m16:13:25.549961 [info ] [MainThread]: Using profiles.yml file at C:\Users\salma.mahmoud\.dbt\profiles.yml
[0m16:13:25.549961 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\salma.mahmoud\cube\dbt-semantic-layer\dbt_project.yml
[0m16:13:25.551088 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m16:13:25.552111 [debug] [MainThread]: Command `dbt debug` failed at 16:13:25.551088 after 1.23 seconds
[0m16:13:25.552111 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C62BD957F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C63C130350>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C63D86B470>]}
[0m16:13:25.552111 [debug] [MainThread]: Flushing usage events
[0m16:13:26.542306 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m16:20:24.888459 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002342FD6DE80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002342FD6DF40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002342FD6E030>]}


============================== 16:20:24.893027 | 192b5d92-f415-4493-991b-bb1a92646a43 ==============================
[0m16:20:24.893027 [info ] [MainThread]: Running with dbt=1.10.5
[0m16:20:24.894057 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\salma.mahmoud\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt debug', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m16:20:24.920752 [info ] [MainThread]: dbt version: 1.10.5
[0m16:20:24.921744 [info ] [MainThread]: python version: 3.12.4
[0m16:20:24.921744 [info ] [MainThread]: python path: C:\Program Files\Python312\python.exe
[0m16:20:24.923254 [info ] [MainThread]: os info: Windows-11-10.0.26100-SP0
[0m16:20:25.986422 [info ] [MainThread]: Using profiles dir at C:\Users\salma.mahmoud\.dbt
[0m16:20:25.986422 [info ] [MainThread]: Using profiles.yml file at C:\Users\salma.mahmoud\.dbt\profiles.yml
[0m16:20:25.987429 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\salma.mahmoud\cube\dbt-semantic-layer\dbt_project.yml
[0m16:20:25.987429 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m16:20:25.988420 [debug] [MainThread]: Command `dbt debug` failed at 16:20:25.988420 after 1.29 seconds
[0m16:20:25.989498 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002342FBAF410>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023442555AF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002342FCD6120>]}
[0m16:20:25.989498 [debug] [MainThread]: Flushing usage events
[0m16:20:27.164396 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m16:21:07.714197 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A34EE9FFB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A351855D60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A3518561B0>]}


============================== 16:21:07.718199 | 0c558b5e-29d9-4215-a4ff-37bb39d01f6f ==============================
[0m16:21:07.718199 [info ] [MainThread]: Running with dbt=1.10.5
[0m16:21:07.719195 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\salma.mahmoud\\.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'introspect': 'True', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt debug', 'send_anonymous_usage_stats': 'True'}
[0m16:21:07.740702 [info ] [MainThread]: dbt version: 1.10.5
[0m16:21:07.740702 [info ] [MainThread]: python version: 3.12.4
[0m16:21:07.741709 [info ] [MainThread]: python path: C:\Program Files\Python312\python.exe
[0m16:21:07.741709 [info ] [MainThread]: os info: Windows-11-10.0.26100-SP0
[0m16:21:08.796013 [info ] [MainThread]: Using profiles dir at C:\Users\salma.mahmoud\.dbt
[0m16:21:08.797011 [info ] [MainThread]: Using profiles.yml file at C:\Users\salma.mahmoud\.dbt\profiles.yml
[0m16:21:08.798011 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\salma.mahmoud\cube\dbt-semantic-layer\dbt_project.yml
[0m16:21:08.798877 [info ] [MainThread]: adapter type: snowflake
[0m16:21:08.799883 [info ] [MainThread]: adapter version: 1.8.4
[0m16:21:08.799883 [info ] [MainThread]: Configuration:
[0m16:21:08.799883 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m16:21:08.800881 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m16:21:08.801389 [info ] [MainThread]: Required dependencies:
[0m16:21:08.801389 [debug] [MainThread]: Executing "git --help"
[0m16:21:08.845749 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--config-env=<name>=<envvar>] <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m16:21:08.846749 [debug] [MainThread]: STDERR: "b''"
[0m16:21:08.846749 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m16:21:08.848253 [info ] [MainThread]: Connection:
[0m16:21:08.848253 [info ] [MainThread]:   account: RZIRXYJ-RY81273
[0m16:21:08.849274 [info ] [MainThread]:   user: salma
[0m16:21:08.849274 [info ] [MainThread]:   database: lightdash_db
[0m16:21:08.850348 [info ] [MainThread]:   warehouse: compute_wh
[0m16:21:08.850348 [info ] [MainThread]:   role: None
[0m16:21:08.851371 [info ] [MainThread]:   schema: bi
[0m16:21:08.851371 [info ] [MainThread]:   authenticator: None
[0m16:21:08.852384 [info ] [MainThread]:   oauth_client_id: None
[0m16:21:08.852384 [info ] [MainThread]:   query_tag: None
[0m16:21:08.853368 [info ] [MainThread]:   client_session_keep_alive: False
[0m16:21:08.853368 [info ] [MainThread]:   host: None
[0m16:21:08.853368 [info ] [MainThread]:   port: None
[0m16:21:08.854553 [info ] [MainThread]:   proxy_host: None
[0m16:21:08.854553 [info ] [MainThread]:   proxy_port: None
[0m16:21:08.854553 [info ] [MainThread]:   protocol: None
[0m16:21:08.855556 [info ] [MainThread]:   connect_retries: 1
[0m16:21:08.856556 [info ] [MainThread]:   connect_timeout: None
[0m16:21:08.856556 [info ] [MainThread]:   retry_on_database_errors: False
[0m16:21:08.857554 [info ] [MainThread]:   retry_all: False
[0m16:21:08.857554 [info ] [MainThread]:   insecure_mode: False
[0m16:21:08.858561 [info ] [MainThread]:   reuse_connections: None
[0m16:21:08.859571 [info ] [MainThread]: Registered adapter: snowflake=1.8.4
[0m16:21:09.322066 [debug] [MainThread]: Acquiring new snowflake connection 'debug'
[0m16:21:09.323067 [debug] [MainThread]: Using snowflake connection "debug"
[0m16:21:09.324065 [debug] [MainThread]: On debug: select 1 as id
[0m16:21:09.324065 [debug] [MainThread]: Opening a new connection, currently in state init
[0m16:21:12.690313 [debug] [MainThread]: SQL status: SUCCESS 1 in 3.366 seconds
[0m16:21:12.691401 [debug] [MainThread]: On debug: Close
[0m16:21:12.966328 [info ] [MainThread]:   Connection test: [[32mOK connection ok[0m]

[0m16:21:12.967313 [info ] [MainThread]: [31m1 check failed:[0m
[0m16:21:12.968255 [info ] [MainThread]: Project loading failed for the following reason:
 project path <C:\Users\salma.mahmoud\cube\dbt-semantic-layer\dbt_project.yml> not found

[0m16:21:12.969227 [debug] [MainThread]: Command `dbt debug` failed at 16:21:12.969227 after 5.43 seconds
[0m16:21:12.969227 [debug] [MainThread]: Connection 'debug' was properly closed.
[0m16:21:12.970226 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A35212CAD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A3513F7470>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A3510F7B60>]}
[0m16:21:12.971226 [debug] [MainThread]: Flushing usage events
[0m16:21:14.019218 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m16:54:57.565951 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000252CC5AC920>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000252CC5ACA10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000252CC5AC980>]}


============================== 16:54:57.571106 | b93327d4-0919-4845-8ee5-64f28b09b463 ==============================
[0m16:54:57.571106 [info ] [MainThread]: Running with dbt=1.10.5
[0m16:54:57.571106 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\salma.mahmoud\\.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'C:\\Users\\salma.mahmoud\\cube\\dbt-semantic-layer\\logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'target_path': 'None', 'invocation_command': 'dbt debug', 'send_anonymous_usage_stats': 'True'}
[0m16:54:57.608579 [info ] [MainThread]: dbt version: 1.10.5
[0m16:54:57.608579 [info ] [MainThread]: python version: 3.12.4
[0m16:54:57.609719 [info ] [MainThread]: python path: C:\Program Files\Python312\python.exe
[0m16:54:57.609719 [info ] [MainThread]: os info: Windows-11-10.0.26100-SP0
[0m16:54:59.078895 [info ] [MainThread]: Using profiles dir at C:\Users\salma.mahmoud\.dbt
[0m16:54:59.078895 [info ] [MainThread]: Using profiles.yml file at C:\Users\salma.mahmoud\.dbt\profiles.yml
[0m16:54:59.078895 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\salma.mahmoud\cube\dbt-semantic-layer\dbt_project.yml
[0m16:54:59.078895 [info ] [MainThread]: adapter type: snowflake
[0m16:54:59.078895 [info ] [MainThread]: adapter version: 1.8.4
[0m16:54:59.169027 [info ] [MainThread]: Configuration:
[0m16:54:59.169027 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m16:54:59.169027 [info ] [MainThread]:   dbt_project.yml file [[32mOK found and valid[0m]
[0m16:54:59.169027 [info ] [MainThread]: Required dependencies:
[0m16:54:59.169027 [debug] [MainThread]: Executing "git --help"
[0m16:54:59.211875 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--config-env=<name>=<envvar>] <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m16:54:59.211875 [debug] [MainThread]: STDERR: "b''"
[0m16:54:59.212962 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m16:54:59.212962 [info ] [MainThread]: Connection:
[0m16:54:59.213939 [info ] [MainThread]:   account: RZIRXYJ-RY81273
[0m16:54:59.213939 [info ] [MainThread]:   user: salma
[0m16:54:59.214943 [info ] [MainThread]:   database: lightdash_db
[0m16:54:59.214943 [info ] [MainThread]:   warehouse: compute_wh
[0m16:54:59.216065 [info ] [MainThread]:   role: None
[0m16:54:59.216065 [info ] [MainThread]:   schema: bi
[0m16:54:59.216999 [info ] [MainThread]:   authenticator: None
[0m16:54:59.216999 [info ] [MainThread]:   oauth_client_id: None
[0m16:54:59.216999 [info ] [MainThread]:   query_tag: None
[0m16:54:59.218281 [info ] [MainThread]:   client_session_keep_alive: False
[0m16:54:59.218786 [info ] [MainThread]:   host: None
[0m16:54:59.218786 [info ] [MainThread]:   port: None
[0m16:54:59.219790 [info ] [MainThread]:   proxy_host: None
[0m16:54:59.219790 [info ] [MainThread]:   proxy_port: None
[0m16:54:59.219790 [info ] [MainThread]:   protocol: None
[0m16:54:59.220790 [info ] [MainThread]:   connect_retries: 1
[0m16:54:59.220790 [info ] [MainThread]:   connect_timeout: None
[0m16:54:59.221790 [info ] [MainThread]:   retry_on_database_errors: False
[0m16:54:59.221790 [info ] [MainThread]:   retry_all: False
[0m16:54:59.221790 [info ] [MainThread]:   insecure_mode: False
[0m16:54:59.222790 [info ] [MainThread]:   reuse_connections: None
[0m16:54:59.222790 [info ] [MainThread]: Registered adapter: snowflake=1.8.4
[0m16:54:59.469082 [debug] [MainThread]: Acquiring new snowflake connection 'debug'
[0m16:54:59.469082 [debug] [MainThread]: Using snowflake connection "debug"
[0m16:54:59.469082 [debug] [MainThread]: On debug: select 1 as id
[0m16:54:59.469082 [debug] [MainThread]: Opening a new connection, currently in state init
[0m16:55:00.768429 [debug] [MainThread]: SQL status: SUCCESS 1 in 1.298 seconds
[0m16:55:00.771052 [debug] [MainThread]: On debug: Close
[0m16:55:01.022714 [info ] [MainThread]:   Connection test: [[32mOK connection ok[0m]

[0m16:55:01.024548 [info ] [MainThread]: [32mAll checks passed![0m
[0m16:55:01.026338 [debug] [MainThread]: Command `dbt debug` succeeded at 16:55:01.026338 after 3.66 seconds
[0m16:55:01.028989 [debug] [MainThread]: Connection 'debug' was properly closed.
[0m16:55:01.028989 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000252CC8F5070>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000252CCE4A360>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000252DDE24AA0>]}
[0m16:55:01.030739 [debug] [MainThread]: Flushing usage events
[0m16:55:02.168772 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m16:58:24.726632 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000253126A7F80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002531080FFE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000253130A5CD0>]}


============================== 16:58:24.726632 | 7da7a3c9-9a10-4672-b8f5-1724769ac5f4 ==============================
[0m16:58:24.726632 [info ] [MainThread]: Running with dbt=1.10.5
[0m16:58:24.726632 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'C:\\Users\\salma.mahmoud\\cube\\dbt-semantic-layer\\logs', 'profiles_dir': 'C:\\Users\\salma.mahmoud\\.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m16:58:25.843481 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '7da7a3c9-9a10-4672-b8f5-1724769ac5f4', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025324733FE0>]}
[0m16:58:25.890870 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '7da7a3c9-9a10-4672-b8f5-1724769ac5f4', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002532481BE00>]}
[0m16:58:25.890870 [info ] [MainThread]: Registered adapter: snowflake=1.8.4
[0m16:58:26.163273 [debug] [MainThread]: checksum: fa4c2685620973c5adba0a491aa9c06e8cf48c9113a5280b45b6efa706ae8f4b, vars: {}, profile: , target: , version: 1.10.5
[0m16:58:26.165277 [info ] [MainThread]: Unable to do partial parsing because saved manifest not found. Starting full parse.
[0m16:58:26.165277 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'partial_parser', 'label': '7da7a3c9-9a10-4672-b8f5-1724769ac5f4', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025312A649E0>]}
[0m16:58:27.856901 [warn ] [MainThread]: [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.bi.example
[0m16:58:27.856901 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': '7da7a3c9-9a10-4672-b8f5-1724769ac5f4', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025325CDC230>]}
[0m16:58:27.892014 [debug] [MainThread]: Wrote artifact WritableManifest to C:\Users\salma.mahmoud\cube\dbt-semantic-layer\target\manifest.json
[0m16:58:27.908043 [debug] [MainThread]: Wrote artifact SemanticManifest to C:\Users\salma.mahmoud\cube\dbt-semantic-layer\target\semantic_manifest.json
[0m16:58:27.935822 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': '7da7a3c9-9a10-4672-b8f5-1724769ac5f4', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025325D022D0>]}
[0m16:58:27.935822 [info ] [MainThread]: Found 464 macros
[0m16:58:27.936824 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': '7da7a3c9-9a10-4672-b8f5-1724769ac5f4', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025325C64E60>]}
[0m16:58:27.938839 [warn ] [MainThread]: Nothing to do. Try checking your model configs and model specification args
[0m16:58:27.938839 [debug] [MainThread]: Command end result
[0m16:58:27.954098 [debug] [MainThread]: Wrote artifact WritableManifest to C:\Users\salma.mahmoud\cube\dbt-semantic-layer\target\manifest.json
[0m16:58:27.955086 [debug] [MainThread]: Wrote artifact SemanticManifest to C:\Users\salma.mahmoud\cube\dbt-semantic-layer\target\semantic_manifest.json
[0m16:58:27.959487 [debug] [MainThread]: Wrote artifact RunExecutionResult to C:\Users\salma.mahmoud\cube\dbt-semantic-layer\target\run_results.json
[0m16:58:27.960471 [debug] [MainThread]: Command `dbt run` succeeded at 16:58:27.960471 after 3.41 seconds
[0m16:58:27.960471 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000253126A7F80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025312D8AE70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025323A7CBC0>]}
[0m16:58:27.961544 [debug] [MainThread]: Flushing usage events
[0m16:58:29.203954 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m16:58:55.353845 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000224A16F9FA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000224A19C9970>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002249F04AA80>]}


============================== 16:58:55.369861 | be5d3c1f-c24b-4146-b502-47aa11636d18 ==============================
[0m16:58:55.369861 [info ] [MainThread]: Running with dbt=1.10.5
[0m16:58:55.369861 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'C:\\Users\\salma.mahmoud\\cube\\dbt-semantic-layer\\logs', 'profiles_dir': 'C:\\Users\\salma.mahmoud\\.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m16:58:56.326222 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': 'be5d3c1f-c24b-4146-b502-47aa11636d18', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000224A1ADE240>]}
[0m16:58:56.374549 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': 'be5d3c1f-c24b-4146-b502-47aa11636d18', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000224B3193E00>]}
[0m16:58:56.374549 [info ] [MainThread]: Registered adapter: snowflake=1.8.4
[0m16:58:56.571773 [debug] [MainThread]: checksum: fa4c2685620973c5adba0a491aa9c06e8cf48c9113a5280b45b6efa706ae8f4b, vars: {}, profile: , target: , version: 1.10.5
[0m16:58:56.674828 [debug] [MainThread]: Partial parsing enabled: 0 files deleted, 0 files added, 0 files changed.
[0m16:58:56.674828 [debug] [MainThread]: Partial parsing enabled, no changes found, skipping parsing
[0m16:58:56.676832 [warn ] [MainThread]: [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.bi.example
[0m16:58:56.676832 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': 'be5d3c1f-c24b-4146-b502-47aa11636d18', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000224A1FA3260>]}
[0m16:58:56.712046 [debug] [MainThread]: Wrote artifact WritableManifest to C:\Users\salma.mahmoud\cube\dbt-semantic-layer\target\manifest.json
[0m16:58:56.712998 [debug] [MainThread]: Wrote artifact SemanticManifest to C:\Users\salma.mahmoud\cube\dbt-semantic-layer\target\semantic_manifest.json
[0m16:58:56.734842 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': 'be5d3c1f-c24b-4146-b502-47aa11636d18', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000224B3335940>]}
[0m16:58:56.734842 [info ] [MainThread]: Found 464 macros
[0m16:58:56.735875 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': 'be5d3c1f-c24b-4146-b502-47aa11636d18', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000224B3305040>]}
[0m16:58:56.736851 [warn ] [MainThread]: Nothing to do. Try checking your model configs and model specification args
[0m16:58:56.738956 [debug] [MainThread]: Command end result
[0m16:58:56.740936 [debug] [MainThread]: Wrote artifact WritableManifest to C:\Users\salma.mahmoud\cube\dbt-semantic-layer\target\manifest.json
[0m16:58:56.740936 [debug] [MainThread]: Wrote artifact SemanticManifest to C:\Users\salma.mahmoud\cube\dbt-semantic-layer\target\semantic_manifest.json
[0m16:58:56.740936 [debug] [MainThread]: Wrote artifact RunExecutionResult to C:\Users\salma.mahmoud\cube\dbt-semantic-layer\target\run_results.json
[0m16:58:56.740936 [debug] [MainThread]: Command `dbt run` succeeded at 16:58:56.740936 after 1.54 seconds
[0m16:58:56.756640 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000224A16F9FA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000224A1A7E9C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000224B31F9C70>]}
[0m16:58:56.756640 [debug] [MainThread]: Flushing usage events
[0m16:58:57.973862 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m17:05:34.365528 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E6D146EF60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E6D11529C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E6D146CAD0>]}


============================== 17:05:34.372112 | 6820b028-e463-4ce1-8375-69797efc5f1b ==============================
[0m17:05:34.372112 [info ] [MainThread]: Running with dbt=1.10.5
[0m17:05:34.373120 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'C:\\Users\\salma.mahmoud\\cube\\dbt-semantic-layer\\logs', 'profiles_dir': 'C:\\Users\\salma.mahmoud\\.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt run', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m17:05:35.427199 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '6820b028-e463-4ce1-8375-69797efc5f1b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E6D18FAED0>]}
[0m17:05:35.492308 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '6820b028-e463-4ce1-8375-69797efc5f1b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E6D12BAFC0>]}
[0m17:05:35.493307 [info ] [MainThread]: Registered adapter: snowflake=1.8.4
[0m17:05:35.780044 [debug] [MainThread]: checksum: fa4c2685620973c5adba0a491aa9c06e8cf48c9113a5280b45b6efa706ae8f4b, vars: {}, profile: , target: , version: 1.10.5
[0m17:05:35.850626 [debug] [MainThread]: Partial parsing enabled: 0 files deleted, 0 files added, 0 files changed.
[0m17:05:35.850626 [debug] [MainThread]: Partial parsing enabled, no changes found, skipping parsing
[0m17:05:35.851624 [warn ] [MainThread]: [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.bi.example
[0m17:05:35.857110 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': '6820b028-e463-4ce1-8375-69797efc5f1b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E6D1CB5610>]}
[0m17:05:35.893241 [debug] [MainThread]: Wrote artifact WritableManifest to C:\Users\salma.mahmoud\cube\dbt-semantic-layer\target\manifest.json
[0m17:05:35.894328 [debug] [MainThread]: Wrote artifact SemanticManifest to C:\Users\salma.mahmoud\cube\dbt-semantic-layer\target\semantic_manifest.json
[0m17:05:35.924512 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': '6820b028-e463-4ce1-8375-69797efc5f1b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E6E3F933B0>]}
[0m17:05:35.924512 [info ] [MainThread]: Found 464 macros
[0m17:05:35.925512 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': '6820b028-e463-4ce1-8375-69797efc5f1b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E6E3D2EA20>]}
[0m17:05:35.926513 [warn ] [MainThread]: Nothing to do. Try checking your model configs and model specification args
[0m17:05:35.928240 [debug] [MainThread]: Command end result
[0m17:05:35.942884 [debug] [MainThread]: Wrote artifact WritableManifest to C:\Users\salma.mahmoud\cube\dbt-semantic-layer\target\manifest.json
[0m17:05:35.946213 [debug] [MainThread]: Wrote artifact SemanticManifest to C:\Users\salma.mahmoud\cube\dbt-semantic-layer\target\semantic_manifest.json
[0m17:05:35.948508 [debug] [MainThread]: Wrote artifact RunExecutionResult to C:\Users\salma.mahmoud\cube\dbt-semantic-layer\target\run_results.json
[0m17:05:35.950132 [debug] [MainThread]: Command `dbt run` succeeded at 17:05:35.950132 after 1.80 seconds
[0m17:05:35.950132 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E6CEA0AA80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E6E2BC2870>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E6D19AD6D0>]}
[0m17:05:35.951229 [debug] [MainThread]: Flushing usage events
[0m17:05:37.478460 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m17:18:27.220623 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D5C1ECBF80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D5C2742240>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D5BFCBC050>]}


============================== 17:18:27.220623 | 1f7d17f4-a22c-4c5b-8f5a-902402a9dc4f ==============================
[0m17:18:27.220623 [info ] [MainThread]: Running with dbt=1.10.5
[0m17:18:27.220623 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': 'C:\\Users\\salma.mahmoud\\.dbt', 'log_path': 'C:\\Users\\salma.mahmoud\\cube\\dbt-semantic-layer\\logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt run', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True'}
[0m17:18:28.228174 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '1f7d17f4-a22c-4c5b-8f5a-902402a9dc4f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D5D331AC30>]}
[0m17:18:28.276266 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '1f7d17f4-a22c-4c5b-8f5a-902402a9dc4f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D5D3D138C0>]}
[0m17:18:28.276266 [info ] [MainThread]: Registered adapter: snowflake=1.8.4
[0m17:18:28.481957 [debug] [MainThread]: checksum: fa4c2685620973c5adba0a491aa9c06e8cf48c9113a5280b45b6efa706ae8f4b, vars: {}, profile: , target: , version: 1.10.5
[0m17:18:28.505495 [info ] [MainThread]: Unable to do partial parsing because a project config has changed
[0m17:18:28.505495 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'partial_parser', 'label': '1f7d17f4-a22c-4c5b-8f5a-902402a9dc4f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D5C25FC620>]}
[0m17:18:29.426880 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': '1f7d17f4-a22c-4c5b-8f5a-902402a9dc4f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D5D508F5C0>]}
[0m17:18:29.474893 [debug] [MainThread]: Wrote artifact WritableManifest to C:\Users\salma.mahmoud\cube\dbt-semantic-layer\target\manifest.json
[0m17:18:29.474893 [debug] [MainThread]: Wrote artifact SemanticManifest to C:\Users\salma.mahmoud\cube\dbt-semantic-layer\target\semantic_manifest.json
[0m17:18:29.507476 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': '1f7d17f4-a22c-4c5b-8f5a-902402a9dc4f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D5D53DA0F0>]}
[0m17:18:29.507476 [info ] [MainThread]: Found 2 models, 1 exposure, 464 macros
[0m17:18:29.507476 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': '1f7d17f4-a22c-4c5b-8f5a-902402a9dc4f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D5D4EEF4D0>]}
[0m17:18:29.507476 [info ] [MainThread]: 
[0m17:18:29.507476 [info ] [MainThread]: Concurrency: 10 threads (target='dev')
[0m17:18:29.507476 [info ] [MainThread]: 
[0m17:18:29.507476 [debug] [MainThread]: Acquiring new snowflake connection 'master'
[0m17:18:29.523543 [debug] [ThreadPool]: Acquiring new snowflake connection 'list_lightdash_db'
[0m17:18:29.529961 [debug] [ThreadPool]: Using snowflake connection "list_lightdash_db"
[0m17:18:29.529961 [debug] [ThreadPool]: On list_lightdash_db: /* {"app": "dbt", "dbt_version": "1.10.5", "profile_name": "bi", "target_name": "dev", "connection_name": "list_lightdash_db"} */
show terse schemas in database lightdash_db
    limit 10000
[0m17:18:29.529961 [debug] [ThreadPool]: Opening a new connection, currently in state init
[0m17:18:30.849772 [debug] [ThreadPool]: SQL status: SUCCESS 3 in 1.316 seconds
[0m17:18:30.849772 [debug] [ThreadPool]: On list_lightdash_db: Close
[0m17:18:31.154949 [debug] [ThreadPool]: Acquiring new snowflake connection 'list_lightdash_db_bi'
[0m17:18:31.161952 [debug] [ThreadPool]: Using snowflake connection "list_lightdash_db_bi"
[0m17:18:31.161952 [debug] [ThreadPool]: On list_lightdash_db_bi: /* {"app": "dbt", "dbt_version": "1.10.5", "profile_name": "bi", "target_name": "dev", "connection_name": "list_lightdash_db_bi"} */
show objects in lightdash_db.bi limit 10000
[0m17:18:31.161952 [debug] [ThreadPool]: Opening a new connection, currently in state init
[0m17:18:32.132240 [debug] [ThreadPool]: SQL status: SUCCESS 0 in 0.973 seconds
[0m17:18:32.141203 [debug] [ThreadPool]: On list_lightdash_db_bi: Close
[0m17:18:32.393068 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': '1f7d17f4-a22c-4c5b-8f5a-902402a9dc4f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D5D3E15BE0>]}
[0m17:18:32.430248 [debug] [Thread-1 (]: Began running node model.bi.base_bank_failures
[0m17:18:32.430248 [info ] [Thread-1 (]: 1 of 2 START sql view model bi.base_bank_failures .............................. [RUN]
[0m17:18:32.430248 [debug] [Thread-1 (]: Acquiring new snowflake connection 'model.bi.base_bank_failures'
[0m17:18:32.430248 [debug] [Thread-1 (]: Began compiling node model.bi.base_bank_failures
[0m17:18:32.430248 [debug] [Thread-1 (]: Writing injected SQL for node "model.bi.base_bank_failures"
[0m17:18:32.430248 [debug] [Thread-1 (]: Began executing node model.bi.base_bank_failures
[0m17:18:32.461488 [debug] [Thread-1 (]: Writing runtime sql for node "model.bi.base_bank_failures"
[0m17:18:32.461488 [debug] [Thread-1 (]: Using snowflake connection "model.bi.base_bank_failures"
[0m17:18:32.461488 [debug] [Thread-1 (]: On model.bi.base_bank_failures: /* {"app": "dbt", "dbt_version": "1.10.5", "profile_name": "bi", "target_name": "dev", "node_id": "model.bi.base_bank_failures"} */
create or replace   view lightdash_db.bi.base_bank_failures
  
   as (
    SELECT *
FROM bank_failures
  );
[0m17:18:32.461488 [debug] [Thread-1 (]: Opening a new connection, currently in state init
[0m17:18:33.434445 [debug] [Thread-1 (]: Snowflake adapter: Snowflake query id: 01bde1da-0000-2aef-0000-00000c9163d1
[0m17:18:33.434445 [debug] [Thread-1 (]: Snowflake adapter: Snowflake error: 002003 (42S02): SQL compilation error:
Object 'LIGHTDASH_DB.BI.BANK_FAILURES' does not exist or not authorized.
[0m17:18:33.434445 [debug] [Thread-1 (]: On model.bi.base_bank_failures: Close
[0m17:18:33.756095 [debug] [Thread-1 (]: Database Error in model base_bank_failures (bi/models\base_bank_failures.sql)
  002003 (42S02): SQL compilation error:
  Object 'LIGHTDASH_DB.BI.BANK_FAILURES' does not exist or not authorized.
  compiled code at target\run\bi\bi/models\base_bank_failures.sql
[0m17:18:33.756095 [debug] [Thread-1 (]: Sending event: {'category': 'dbt', 'action': 'run_model', 'label': '1f7d17f4-a22c-4c5b-8f5a-902402a9dc4f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D5D543CB60>]}
[0m17:18:33.756095 [error] [Thread-1 (]: 1 of 2 ERROR creating sql view model bi.base_bank_failures ..................... [[31mERROR[0m in 1.33s]
[0m17:18:33.756095 [debug] [Thread-1 (]: Finished running node model.bi.base_bank_failures
[0m17:18:33.756095 [debug] [Thread-13 ]: Marking all children of 'model.bi.base_bank_failures' to be skipped because of status 'error'.  Reason: Database Error in model base_bank_failures (bi/models\base_bank_failures.sql)
  002003 (42S02): SQL compilation error:
  Object 'LIGHTDASH_DB.BI.BANK_FAILURES' does not exist or not authorized.
  compiled code at target\run\bi\bi/models\base_bank_failures.sql.
[0m17:18:33.756095 [debug] [Thread-3 (]: Began running node model.bi.clean_bank_failures
[0m17:18:33.756095 [info ] [Thread-3 (]: 2 of 2 SKIP relation bi.clean_bank_failures .................................... [[33mSKIP[0m]
[0m17:18:33.756095 [debug] [Thread-3 (]: Finished running node model.bi.clean_bank_failures
[0m17:18:33.756095 [debug] [MainThread]: Connection 'master' was properly closed.
[0m17:18:33.756095 [debug] [MainThread]: Connection 'list_lightdash_db' was properly closed.
[0m17:18:33.756095 [debug] [MainThread]: Connection 'list_lightdash_db_bi' was properly closed.
[0m17:18:33.756095 [debug] [MainThread]: Connection 'model.bi.base_bank_failures' was properly closed.
[0m17:18:33.756095 [info ] [MainThread]: 
[0m17:18:33.756095 [info ] [MainThread]: Finished running 2 view models in 0 hours 0 minutes and 4.25 seconds (4.25s).
[0m17:18:33.769737 [debug] [MainThread]: Command end result
[0m17:18:33.782907 [debug] [MainThread]: Wrote artifact WritableManifest to C:\Users\salma.mahmoud\cube\dbt-semantic-layer\target\manifest.json
[0m17:18:33.782907 [debug] [MainThread]: Wrote artifact SemanticManifest to C:\Users\salma.mahmoud\cube\dbt-semantic-layer\target\semantic_manifest.json
[0m17:18:33.782907 [debug] [MainThread]: Wrote artifact RunExecutionResult to C:\Users\salma.mahmoud\cube\dbt-semantic-layer\target\run_results.json
[0m17:18:33.782907 [info ] [MainThread]: 
[0m17:18:33.782907 [info ] [MainThread]: [31mCompleted with 1 error, 0 partial successes, and 0 warnings:[0m
[0m17:18:33.792807 [info ] [MainThread]: 
[0m17:18:33.793817 [error] [MainThread]: [31mFailure in model base_bank_failures (bi/models\base_bank_failures.sql)[0m
[0m17:18:33.794231 [error] [MainThread]:   Database Error in model base_bank_failures (bi/models\base_bank_failures.sql)
  002003 (42S02): SQL compilation error:
  Object 'LIGHTDASH_DB.BI.BANK_FAILURES' does not exist or not authorized.
  compiled code at target\run\bi\bi/models\base_bank_failures.sql
[0m17:18:33.794231 [info ] [MainThread]: 
[0m17:18:33.794231 [info ] [MainThread]:   compiled code at target\compiled\bi\bi/models\base_bank_failures.sql
[0m17:18:33.794231 [info ] [MainThread]: 
[0m17:18:33.794231 [info ] [MainThread]: Done. PASS=0 WARN=0 ERROR=1 SKIP=1 NO-OP=0 TOTAL=2
[0m17:18:33.798359 [debug] [MainThread]: Command `dbt run` failed at 17:18:33.798359 after 6.75 seconds
[0m17:18:33.798359 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D5C2A18F20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D5D4EEFC20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D5C29B4EF0>]}
[0m17:18:33.798359 [debug] [MainThread]: Flushing usage events
[0m17:18:35.083176 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m17:46:09.799005 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000180D608FE90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000180D8A0F770>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000180D8A0FB90>]}


============================== 17:46:09.799005 | c61ab5c7-34de-4e43-8e93-f4d40d23f145 ==============================
[0m17:46:09.799005 [info ] [MainThread]: Running with dbt=1.10.5
[0m17:46:09.799005 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\salma.mahmoud\\.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'C:\\Users\\salma.mahmoud\\cube\\dbt-semantic-layer\\logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m17:46:11.335298 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': 'c61ab5c7-34de-4e43-8e93-f4d40d23f145', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000180D608FE90>]}
[0m17:46:11.383288 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': 'c61ab5c7-34de-4e43-8e93-f4d40d23f145', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000180D8B57C80>]}
[0m17:46:11.383288 [info ] [MainThread]: Registered adapter: snowflake=1.8.4
[0m17:46:11.600802 [debug] [MainThread]: checksum: fa4c2685620973c5adba0a491aa9c06e8cf48c9113a5280b45b6efa706ae8f4b, vars: {}, profile: , target: , version: 1.10.5
[0m17:46:11.757194 [debug] [MainThread]: Partial parsing enabled: 0 files deleted, 0 files added, 1 files changed.
[0m17:46:11.757717 [debug] [MainThread]: Partial parsing: updated file: bi://bi/models\base_bank_failures.sql
[0m17:46:11.911179 [error] [MainThread]: Encountered an error:
Compilation Error
  Model 'model.bi.base_bank_failures' (bi/models\base_bank_failures.sql) depends on a source named 'bi.bank_failures' which was not found
[0m17:46:11.911179 [debug] [MainThread]: Command `dbt run` failed at 17:46:11.911179 after 2.30 seconds
[0m17:46:11.911179 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000180D8F51100>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000180EA3016D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000180EA1108F0>]}
[0m17:46:11.911179 [debug] [MainThread]: Flushing usage events
[0m17:46:13.078641 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m17:46:43.180199 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D55CCAC950>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D55CCACA10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D55CCAE810>]}


============================== 17:46:43.180199 | a1fa5235-d7d8-43f2-bede-6e03dc517d03 ==============================
[0m17:46:43.180199 [info ] [MainThread]: Running with dbt=1.10.5
[0m17:46:43.191020 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'C:\\Users\\salma.mahmoud\\cube\\dbt-semantic-layer\\logs', 'profiles_dir': 'C:\\Users\\salma.mahmoud\\.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt run', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True'}
[0m17:46:44.194959 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': 'a1fa5235-d7d8-43f2-bede-6e03dc517d03', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D56E40D010>]}
[0m17:46:44.242174 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': 'a1fa5235-d7d8-43f2-bede-6e03dc517d03', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D56E0102C0>]}
[0m17:46:44.242174 [info ] [MainThread]: Registered adapter: snowflake=1.8.4
[0m17:46:44.491379 [debug] [MainThread]: checksum: fa4c2685620973c5adba0a491aa9c06e8cf48c9113a5280b45b6efa706ae8f4b, vars: {}, profile: , target: , version: 1.10.5
[0m17:46:44.587799 [debug] [MainThread]: Partial parsing enabled: 0 files deleted, 0 files added, 0 files changed.
[0m17:46:44.588795 [debug] [MainThread]: Partial parsing enabled, no changes found, skipping parsing
[0m17:46:44.603322 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': 'a1fa5235-d7d8-43f2-bede-6e03dc517d03', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D56E56E240>]}
[0m17:46:44.650164 [debug] [MainThread]: Wrote artifact WritableManifest to C:\Users\salma.mahmoud\cube\dbt-semantic-layer\target\manifest.json
[0m17:46:44.650164 [debug] [MainThread]: Wrote artifact SemanticManifest to C:\Users\salma.mahmoud\cube\dbt-semantic-layer\target\semantic_manifest.json
[0m17:46:44.691625 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': 'a1fa5235-d7d8-43f2-bede-6e03dc517d03', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D56F72DE50>]}
[0m17:46:44.691625 [info ] [MainThread]: Found 2 models, 1 exposure, 464 macros
[0m17:46:44.697554 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': 'a1fa5235-d7d8-43f2-bede-6e03dc517d03', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D56CFE5670>]}
[0m17:46:44.697554 [info ] [MainThread]: 
[0m17:46:44.697554 [info ] [MainThread]: Concurrency: 10 threads (target='dev')
[0m17:46:44.697554 [info ] [MainThread]: 
[0m17:46:44.697554 [debug] [MainThread]: Acquiring new snowflake connection 'master'
[0m17:46:44.697554 [debug] [ThreadPool]: Acquiring new snowflake connection 'list_lightdash_db'
[0m17:46:44.714137 [debug] [ThreadPool]: Using snowflake connection "list_lightdash_db"
[0m17:46:44.715380 [debug] [ThreadPool]: On list_lightdash_db: /* {"app": "dbt", "dbt_version": "1.10.5", "profile_name": "bi", "target_name": "dev", "connection_name": "list_lightdash_db"} */
show terse schemas in database lightdash_db
    limit 10000
[0m17:46:44.715761 [debug] [ThreadPool]: Opening a new connection, currently in state init
[0m17:46:46.187302 [debug] [ThreadPool]: SQL status: SUCCESS 3 in 1.472 seconds
[0m17:46:46.190304 [debug] [ThreadPool]: On list_lightdash_db: Close
[0m17:46:46.421936 [debug] [ThreadPool]: Acquiring new snowflake connection 'list_lightdash_db_bi'
[0m17:46:46.437846 [debug] [ThreadPool]: Using snowflake connection "list_lightdash_db_bi"
[0m17:46:46.437846 [debug] [ThreadPool]: On list_lightdash_db_bi: /* {"app": "dbt", "dbt_version": "1.10.5", "profile_name": "bi", "target_name": "dev", "connection_name": "list_lightdash_db_bi"} */
show objects in lightdash_db.bi limit 10000
[0m17:46:46.437846 [debug] [ThreadPool]: Opening a new connection, currently in state init
[0m17:46:47.483115 [debug] [ThreadPool]: SQL status: SUCCESS 1 in 1.046 seconds
[0m17:46:47.491913 [debug] [ThreadPool]: On list_lightdash_db_bi: Close
[0m17:46:47.731003 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': 'a1fa5235-d7d8-43f2-bede-6e03dc517d03', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D55A524DD0>]}
[0m17:46:47.767940 [debug] [Thread-1 (]: Began running node model.bi.base_bank_failures
[0m17:46:47.767940 [info ] [Thread-1 (]: 1 of 2 START sql view model bi.base_bank_failures .............................. [RUN]
[0m17:46:47.767940 [debug] [Thread-1 (]: Acquiring new snowflake connection 'model.bi.base_bank_failures'
[0m17:46:47.767940 [debug] [Thread-1 (]: Began compiling node model.bi.base_bank_failures
[0m17:46:47.767940 [debug] [Thread-1 (]: Writing injected SQL for node "model.bi.base_bank_failures"
[0m17:46:47.767940 [debug] [Thread-1 (]: Began executing node model.bi.base_bank_failures
[0m17:46:47.828439 [debug] [Thread-1 (]: Writing runtime sql for node "model.bi.base_bank_failures"
[0m17:46:47.829819 [debug] [Thread-1 (]: Using snowflake connection "model.bi.base_bank_failures"
[0m17:46:47.831297 [debug] [Thread-1 (]: On model.bi.base_bank_failures: /* {"app": "dbt", "dbt_version": "1.10.5", "profile_name": "bi", "target_name": "dev", "node_id": "model.bi.base_bank_failures"} */
create or replace   view lightdash_db.bi.base_bank_failures
  
   as (
    SELECT *
FROM bank_failures
  );
[0m17:46:47.831297 [debug] [Thread-1 (]: Opening a new connection, currently in state init
[0m17:46:48.931568 [debug] [Thread-1 (]: SQL status: SUCCESS 1 in 1.101 seconds
[0m17:46:48.947402 [debug] [Thread-1 (]: On model.bi.base_bank_failures: Close
[0m17:46:49.183559 [debug] [Thread-1 (]: Sending event: {'category': 'dbt', 'action': 'run_model', 'label': 'a1fa5235-d7d8-43f2-bede-6e03dc517d03', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D55C5E1370>]}
[0m17:46:49.183559 [info ] [Thread-1 (]: 1 of 2 OK created sql view model bi.base_bank_failures ......................... [[32mSUCCESS 1[0m in 1.40s]
[0m17:46:49.183559 [debug] [Thread-1 (]: Finished running node model.bi.base_bank_failures
[0m17:46:49.183559 [debug] [Thread-3 (]: Began running node model.bi.clean_bank_failures
[0m17:46:49.183559 [info ] [Thread-3 (]: 2 of 2 START sql view model bi.clean_bank_failures ............................. [RUN]
[0m17:46:49.183559 [debug] [Thread-3 (]: Acquiring new snowflake connection 'model.bi.clean_bank_failures'
[0m17:46:49.196834 [debug] [Thread-3 (]: Began compiling node model.bi.clean_bank_failures
[0m17:46:49.202810 [debug] [Thread-3 (]: Writing injected SQL for node "model.bi.clean_bank_failures"
[0m17:46:49.207676 [debug] [Thread-3 (]: Began executing node model.bi.clean_bank_failures
[0m17:46:49.213381 [debug] [Thread-3 (]: Writing runtime sql for node "model.bi.clean_bank_failures"
[0m17:46:49.218919 [debug] [Thread-3 (]: Using snowflake connection "model.bi.clean_bank_failures"
[0m17:46:49.219899 [debug] [Thread-3 (]: On model.bi.clean_bank_failures: /* {"app": "dbt", "dbt_version": "1.10.5", "profile_name": "bi", "target_name": "dev", "node_id": "model.bi.clean_bank_failures"} */
create or replace   view lightdash_db.bi.clean_bank_failures
  
   as (
    SELECT
    State,
    COUNT(*) AS total_failures,
    SUM("Assets ($mil.)" ) AS total_assets
FROM
    lightdash_db.bi.base_bank_failures
GROUP BY
    State
  );
[0m17:46:49.219899 [debug] [Thread-3 (]: Opening a new connection, currently in state init
[0m17:46:50.203053 [debug] [Thread-3 (]: SQL status: SUCCESS 1 in 0.984 seconds
[0m17:46:50.203053 [debug] [Thread-3 (]: On model.bi.clean_bank_failures: Close
[0m17:46:50.448187 [debug] [Thread-3 (]: Sending event: {'category': 'dbt', 'action': 'run_model', 'label': 'a1fa5235-d7d8-43f2-bede-6e03dc517d03', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D56FB875C0>]}
[0m17:46:50.448187 [info ] [Thread-3 (]: 2 of 2 OK created sql view model bi.clean_bank_failures ........................ [[32mSUCCESS 1[0m in 1.26s]
[0m17:46:50.464402 [debug] [Thread-3 (]: Finished running node model.bi.clean_bank_failures
[0m17:46:50.464402 [debug] [MainThread]: Connection 'master' was properly closed.
[0m17:46:50.464402 [debug] [MainThread]: Connection 'list_lightdash_db' was properly closed.
[0m17:46:50.464402 [debug] [MainThread]: Connection 'list_lightdash_db_bi' was properly closed.
[0m17:46:50.469007 [debug] [MainThread]: Connection 'model.bi.base_bank_failures' was properly closed.
[0m17:46:50.469007 [debug] [MainThread]: Connection 'model.bi.clean_bank_failures' was properly closed.
[0m17:46:50.469007 [info ] [MainThread]: 
[0m17:46:50.469007 [info ] [MainThread]: Finished running 2 view models in 0 hours 0 minutes and 5.77 seconds (5.77s).
[0m17:46:50.471354 [debug] [MainThread]: Command end result
[0m17:46:50.489457 [debug] [MainThread]: Wrote artifact WritableManifest to C:\Users\salma.mahmoud\cube\dbt-semantic-layer\target\manifest.json
[0m17:46:50.491497 [debug] [MainThread]: Wrote artifact SemanticManifest to C:\Users\salma.mahmoud\cube\dbt-semantic-layer\target\semantic_manifest.json
[0m17:46:50.494562 [debug] [MainThread]: Wrote artifact RunExecutionResult to C:\Users\salma.mahmoud\cube\dbt-semantic-layer\target\run_results.json
[0m17:46:50.494562 [info ] [MainThread]: 
[0m17:46:50.494562 [info ] [MainThread]: [32mCompleted successfully[0m
[0m17:46:50.494562 [info ] [MainThread]: 
[0m17:46:50.498413 [info ] [MainThread]: Done. PASS=2 WARN=0 ERROR=0 SKIP=0 NO-OP=0 TOTAL=2
[0m17:46:50.499418 [debug] [MainThread]: Command `dbt run` succeeded at 17:46:50.499418 after 7.46 seconds
[0m17:46:50.499418 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D56DA0C140>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D56E40DD30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D56D5BC470>]}
[0m17:46:50.500753 [debug] [MainThread]: Flushing usage events
[0m17:46:51.841513 [debug] [MainThread]: An error was encountered while trying to flush usage events
